# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mygui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReidSystem(object):
    def setupUi(self, ReidSystem):
        ReidSystem.setObjectName("ReidSystem")
        ReidSystem.resize(992, 693)
        ReidSystem.setStyleSheet("/*\n"
"Ubuntu Style Sheet for QT Applications\n"
"Author: Jaime A. Quiroga P.\n"
"Company: GTRONICK\n"
"Last updated: 01/10/2021 (dd/mm/yyyy), 15:18.\n"
"Available at: https://github.com/GTRONICK/QSS/blob/master/Ubuntu.qss\n"
"*/\n"
"QMainWindow {\n"
"    background-color:#ffffff;\n"
"}\n"
"QCheckBox {\n"
"    padding:2px;\n"
"}\n"
"QCheckBox:hover {\n"
"    border:1px solid rgb(255,150,60);\n"
"    border-radius:4px;\n"
"    padding: 1px;\n"
"    background-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(190, 90, 50, 50), stop:1 rgba(250, 130, 40, 50));\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border:1px solid rgb(246, 134, 86);\n"
"    border-radius:4px;\n"
"      background-color:rgb(246, 134, 86)\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border-width:1px solid rgb(246, 134, 86);\n"
"    border-radius:4px;\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QColorDialog {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QComboBox {\n"
"    color:rgb(81,72,65);\n"
"    background: #ffffff;\n"
"}\n"
"QComboBox:editable {\n"
"    selection-color:rgb(81,72,65);\n"
"    selection-background-color: #ffffff;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    selection-color: #ffffff;\n"
"    selection-background-color: rgb(246, 134, 86);\n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    color:  #1e1d23;    \n"
"}\n"
"QDateTimeEdit, QDateEdit, QDoubleSpinBox, QFontComboBox {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QDialog {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"\n"
"QLabel,QLineEdit {\n"
"    color:rgb(17,17,17);\n"
"}\n"
"QLineEdit {\n"
"    background-color:rgb(255,255,255);\n"
"    selection-background-color:rgb(236,116,64);\n"
"}\n"
"QMenuBar {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item {\n"
"    padding-top:4px;\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    padding-top:2px;\n"
"    padding-left:2px;\n"
"    padding-right:2px;\n"
"    border-top-width:2px;\n"
"    border-left-width:2px;\n"
"    border-right-width:2px;\n"
"    border-top-right-radius:4px;\n"
"    border-top-left-radius:4px;\n"
"    border-style:solid;\n"
"    background-color:rgb(65,64,59);\n"
"    border-top-color: rgb(47,47,44);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"}\n"
"QMenu {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenu::item {\n"
"    color:rgb(223,219,210);\n"
"    padding:4px 10px 4px 20px;\n"
"}\n"
"QMenu::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"    border-style:solid;\n"
"    border-width:3px;\n"
"    padding:4px 7px 4px 17px;\n"
"    border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"    border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"}\n"
"QPlainTextEdit {\n"
"    border: 1px solid transparent;\n"
"    color:rgb(17,17,17);\n"
"    selection-background-color:rgb(236,116,64);\n"
"    background-color: #FFFFFF;\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px inset rgb(150,150,150); \n"
"    border-radius: 10px;\n"
"    background-color:rgb(221,221,219);\n"
"}\n"
"QProgressBar::chunk:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"    border:1px solid;\n"
"    border-radius:8px;\n"
"    border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"    border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"}\n"
"QPushButton{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    border-bottom-color: rgb(150,150,150);\n"
"    border-right-color: rgb(165,165,165);\n"
"    border-left-color: rgb(165,165,165);\n"
"    border-top-color: rgb(180,180,180);\n"
"    border-style: solid;\n"
"    padding: 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-top-color: rgb(255,150,60);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-bottom-color: rgb(200,70,20);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:default{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-top-color: rgb(255,150,60);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-bottom-color: rgb(200,70,20);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:pressed{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    border-width: 1px;\n"
"    border-top-color: rgba(255,150,60,200);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 200));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 200));\n"
"    border-bottom-color: rgba(200,70,20,200);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:disabled{\n"
"    color:rgb(174,167,159);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(200, 200, 200, 255), stop:1 rgba(230, 230, 230, 255));\n"
"}\n"
"QRadioButton {\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: rgba(246, 134, 86, 255);\n"
"    color: #a9b7c6;\n"
"    background-color:rgba(246, 134, 86, 255);\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: rgb(246, 134, 86);\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QScrollArea {\n"
"    color: white;\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QSlider::groove {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal, QSlider::add-page:vertical {\n"
"     background: white;\n"
"}\n"
"QSlider::sub-page:horizontal, QSlider::sub-page:vertical {\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QStatusBar, QSpinBox {\n"
"    color:rgb(81,72,65);\n"
"}\n"
"QSpinBox {\n"
"    background-color: #ffffff;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    max-height: 20px;\n"
"    border: 1px transparent;\n"
"    margin: 0px 20px 0px 20px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border: 1px solid rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgb(253,253,253);\n"
"    border: 1px solid rgb(255,150,60);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {\n"
"      border: 1px solid rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-left-radius: 7px;\n"
"      border-top-right-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"      border: 1px solid rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::left-arrow:horizontal {\n"
"      border: 1px transparent grey;\n"
"      border-top-left-radius: 3px;\n"
"      border-bottom-left-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::right-arrow:horizontal {\n"
"    border: 1px transparent grey;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"     background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"     background: none;\n"
"} \n"
"QScrollBar:vertical {\n"
"    max-width: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: 1px solid;\n"
"    border-color: rgb(207,207,207);\n"
"    border-bottom-right-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-top-left-radius: 7px;\n"
"    background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(255,150,60);\n"
"      border-bottom-right-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"      border: 1px solid grey;\n"
"      border-bottom-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"      border: 1px solid rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"      border: 1px solid rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"    background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-left-radius: 7px;\n"
"      border-top-right-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"     height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border: 1px solid rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(253,253,253);\n"
"    border: 1px solid rgb(255,150,60);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::up-arrow:vertical {\n"
"    border: 1px transparent grey;\n"
"      border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::down-arrow:vertical {\n"
"      border: 1px transparent grey;\n"
"      border-bottom-left-radius: 3px;\n"
"      border-bottom-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"      background: none;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:rgb(247,246,246);\n"
"}\n"
"QTabWidget::pane {\n"
"    border-color: rgb(180,180,180);\n"
"    background-color:rgb(247,246,246);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"      border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    padding-bottom:2px;\n"
"    padding-top:2px;\n"
"    color:rgb(81,72,65);\n"
"      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(221,218,217,255), stop:1 rgba(240,239,238,255));\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"      border-top-right-radius:4px;\n"
"    border-top-left-radius:4px;\n"
"    border-top-color: rgb(180,180,180);\n"
"    border-left-color: rgb(180,180,180);\n"
"    border-right-color: rgb(180,180,180);\n"
"    border-bottom-color: transparent;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      background-color:rgb(247,246,246);\n"
"      margin-left: 0px;\n"
"      margin-right: 1px;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 1px;\n"
"    margin-right: 1px;\n"
"}\n"
"QTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color:transparent;\n"
"    color:rgb(17,17,17);\n"
"    selection-background-color:rgb(236,116,64);\n"
"}\n"
"QTimeEdit, QToolBox, QToolBox::tab, QToolBox::tab:selected {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(ReidSystem)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.queryID = QtWidgets.QLabel(self.groupBox_3)
        self.queryID.setStyleSheet("QLabel{\n"
"        background-color:rgb(240,240,240);\n"
"        border-radius:6px;\n"
"        border-color:grey grey grey grey;\n"
"        border-style:groove;\n"
"        border-width:2px    \n"
"}\n"
"\n"
"")
        self.queryID.setAlignment(QtCore.Qt.AlignCenter)
        self.queryID.setObjectName("queryID")
        self.verticalLayout_12.addWidget(self.queryID)
        self.query = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.query.setFont(font)
        self.query.setAutoFillBackground(False)
        self.query.setStyleSheet("QLabel{\n"
"        background-color:rgb(240,240,240);\n"
"        border-radius:6px;\n"
"        border-color:grey grey grey grey;\n"
"        border-style:groove;\n"
"        border-width:2px    \n"
"}\n"
"\n"
"")
        self.query.setAlignment(QtCore.Qt.AlignCenter)
        self.query.setObjectName("query")
        self.verticalLayout_12.addWidget(self.query)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 10)
        self.verticalLayout_25.addLayout(self.verticalLayout_12)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.mode = QtWidgets.QComboBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.mode.setFont(font)
        self.mode.setStyleSheet("QComboBox\n"
"{\n"
"        background-color:rgb(255,255,255);\n"
"        border-radius:6px;\n"
"        border-color:grey grey grey grey;\n"
"        border-style:groove;\n"
"        border-width:2px    \n"
"}\n"
"\n"
"")
        self.mode.setObjectName("mode")
        self.mode.addItem("")
        self.mode.addItem("")
        self.horizontalLayout_2.addWidget(self.mode)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.setStretch(0, 15)
        self.horizontalLayout_2.setStretch(1, 29)
        self.horizontalLayout_2.setStretch(2, 80)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_13.addWidget(self.label_2)
        self.command = QtWidgets.QTextBrowser(self.groupBox_4)
        self.command.setStyleSheet("QTextBrowser\n"
"{\n"
"        background-color:rgb(255,255,255);\n"
"        border-radius:6px;\n"
"        border-color:grey grey grey grey;\n"
"        border-style:groove;\n"
"        border-width:2px    \n"
"}\n"
"\n"
"")
        self.command.setObjectName("command")
        self.verticalLayout_13.addWidget(self.command)
        self.verticalLayout_13.setStretch(0, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 7)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.r1text = QtWidgets.QLabel(self.groupBox_2)
        self.r1text.setText("")
        self.r1text.setAlignment(QtCore.Qt.AlignCenter)
        self.r1text.setObjectName("r1text")
        self.verticalLayout.addWidget(self.r1text)
        self.r1photo = QtWidgets.QLabel(self.groupBox_2)
        self.r1photo.setStyleSheet("QLabel{\n"
"        background-color:rgb(240,240,240);\n"
"        border-radius:6px;\n"
"        border-color:grey grey grey grey;\n"
"        border-style:groove;\n"
"        border-width:2px    \n"
"}\n"
"\n"
"")
        self.r1photo.setText("")
        self.r1photo.setObjectName("r1photo")
        self.verticalLayout.addWidget(self.r1photo)
        self.r1text_2 = QtWidgets.QLabel(self.groupBox_2)
        self.r1text_2.setText("")
        self.r1text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.r1text_2.setObjectName("r1text_2")
        self.verticalLayout.addWidget(self.r1text_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 10)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.r2text = QtWidgets.QLabel(self.groupBox_2)
        self.r2text.setText("")
        self.r2text.setAlignment(QtCore.Qt.AlignCenter)
        self.r2text.setObjectName("r2text")
        self.verticalLayout_2.addWidget(self.r2text)
        self.r2photo = QtWidgets.QLabel(self.groupBox_2)
        self.r2photo.setStyleSheet("QLabel{\n"
"        background-color:rgb(240,240,240);\n"
"        border-radius:6px;\n"
"        border-color:grey grey grey grey;\n"
"        border-style:groove;\n"
"        border-width:2px    \n"
"}\n"
"\n"
"")
        self.r2photo.setText("")
        self.r2photo.setObjectName("r2photo")
        self.verticalLayout_2.addWidget(self.r2photo)
        self.r2text_2 = QtWidgets.QLabel(self.groupBox_2)
        self.r2text_2.setText("")
        self.r2text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.r2text_2.setObjectName("r2text_2")
        self.verticalLayout_2.addWidget(self.r2text_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 10)
        self.verticalLayout_2.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.r3text = QtWidgets.QLabel(self.groupBox_2)
        self.r3text.setText("")
        self.r3text.setAlignment(QtCore.Qt.AlignCenter)
        self.r3text.setObjectName("r3text")
        self.verticalLayout_3.addWidget(self.r3text)
        self.r3photo = QtWidgets.QLabel(self.groupBox_2)
        self.r3photo.setStyleSheet("QLabel{\n"
"        background-color:rgb(240,240,240);\n"
"        border-radius:6px;\n"
"        border-color:grey grey grey grey;\n"
"        border-style:groove;\n"
"        border-width:2px    \n"
"}\n"
"\n"
"")
        self.r3photo.setText("")
        self.r3photo.setObjectName("r3photo")
        self.verticalLayout_3.addWidget(self.r3photo)
        self.r3text_2 = QtWidgets.QLabel(self.groupBox_2)
        self.r3text_2.setText("")
        self.r3text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.r3text_2.setObjectName("r3text_2")
        self.verticalLayout_3.addWidget(self.r3text_2)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 10)
        self.verticalLayout_3.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.r4text = QtWidgets.QLabel(self.groupBox_2)
        self.r4text.setText("")
        self.r4text.setAlignment(QtCore.Qt.AlignCenter)
        self.r4text.setObjectName("r4text")
        self.verticalLayout_4.addWidget(self.r4text)
        self.r4photo = QtWidgets.QLabel(self.groupBox_2)
        self.r4photo.setStyleSheet("QLabel{\n"
"        background-color:rgb(240,240,240);\n"
"        border-radius:6px;\n"
"        border-color:grey grey grey grey;\n"
"        border-style:groove;\n"
"        border-width:2px    \n"
"}\n"
"\n"
"")
        self.r4photo.setText("")
        self.r4photo.setObjectName("r4photo")
        self.verticalLayout_4.addWidget(self.r4photo)
        self.r4text_2 = QtWidgets.QLabel(self.groupBox_2)
        self.r4text_2.setText("")
        self.r4text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.r4text_2.setObjectName("r4text_2")
        self.verticalLayout_4.addWidget(self.r4text_2)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 10)
        self.verticalLayout_4.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.r5text = QtWidgets.QLabel(self.groupBox_2)
        self.r5text.setText("")
        self.r5text.setAlignment(QtCore.Qt.AlignCenter)
        self.r5text.setObjectName("r5text")
        self.verticalLayout_5.addWidget(self.r5text)
        self.r5photo = QtWidgets.QLabel(self.groupBox_2)
        self.r5photo.setStyleSheet("QLabel{\n"
"        background-color:rgb(240,240,240);\n"
"        border-radius:6px;\n"
"        border-color:grey grey grey grey;\n"
"        border-style:groove;\n"
"        border-width:2px    \n"
"}\n"
"\n"
"")
        self.r5photo.setText("")
        self.r5photo.setObjectName("r5photo")
        self.verticalLayout_5.addWidget(self.r5photo)
        self.r5text_2 = QtWidgets.QLabel(self.groupBox_2)
        self.r5text_2.setText("")
        self.r5text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.r5text_2.setObjectName("r5text_2")
        self.verticalLayout_5.addWidget(self.r5text_2)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 10)
        self.verticalLayout_5.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.r6text = QtWidgets.QLabel(self.groupBox_2)
        self.r6text.setText("")
        self.r6text.setAlignment(QtCore.Qt.AlignCenter)
        self.r6text.setObjectName("r6text")
        self.verticalLayout_6.addWidget(self.r6text)
        self.r6photo = QtWidgets.QLabel(self.groupBox_2)
        self.r6photo.setStyleSheet("QLabel{\n"
"        background-color:rgb(240,240,240);\n"
"        border-radius:6px;\n"
"        border-color:grey grey grey grey;\n"
"        border-style:groove;\n"
"        border-width:2px    \n"
"}\n"
"\n"
"")
        self.r6photo.setText("")
        self.r6photo.setObjectName("r6photo")
        self.verticalLayout_6.addWidget(self.r6photo)
        self.r6text_2 = QtWidgets.QLabel(self.groupBox_2)
        self.r6text_2.setText("")
        self.r6text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.r6text_2.setObjectName("r6text_2")
        self.verticalLayout_6.addWidget(self.r6text_2)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 10)
        self.verticalLayout_6.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.r7text = QtWidgets.QLabel(self.groupBox_2)
        self.r7text.setText("")
        self.r7text.setAlignment(QtCore.Qt.AlignCenter)
        self.r7text.setObjectName("r7text")
        self.verticalLayout_7.addWidget(self.r7text)
        self.r7photo = QtWidgets.QLabel(self.groupBox_2)
        self.r7photo.setStyleSheet("QLabel{\n"
"        background-color:rgb(240,240,240);\n"
"        border-radius:6px;\n"
"        border-color:grey grey grey grey;\n"
"        border-style:groove;\n"
"        border-width:2px    \n"
"}\n"
"\n"
"")
        self.r7photo.setText("")
        self.r7photo.setObjectName("r7photo")
        self.verticalLayout_7.addWidget(self.r7photo)
        self.r7text_2 = QtWidgets.QLabel(self.groupBox_2)
        self.r7text_2.setText("")
        self.r7text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.r7text_2.setObjectName("r7text_2")
        self.verticalLayout_7.addWidget(self.r7text_2)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 10)
        self.verticalLayout_7.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.r8text = QtWidgets.QLabel(self.groupBox_2)
        self.r8text.setText("")
        self.r8text.setAlignment(QtCore.Qt.AlignCenter)
        self.r8text.setObjectName("r8text")
        self.verticalLayout_8.addWidget(self.r8text)
        self.r8photo = QtWidgets.QLabel(self.groupBox_2)
        self.r8photo.setStyleSheet("QLabel{\n"
"        background-color:rgb(240,240,240);\n"
"        border-radius:6px;\n"
"        border-color:grey grey grey grey;\n"
"        border-style:groove;\n"
"        border-width:2px    \n"
"}\n"
"\n"
"")
        self.r8photo.setText("")
        self.r8photo.setObjectName("r8photo")
        self.verticalLayout_8.addWidget(self.r8photo)
        self.r8text_2 = QtWidgets.QLabel(self.groupBox_2)
        self.r8text_2.setText("")
        self.r8text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.r8text_2.setObjectName("r8text_2")
        self.verticalLayout_8.addWidget(self.r8text_2)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 10)
        self.verticalLayout_8.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.r9text = QtWidgets.QLabel(self.groupBox_2)
        self.r9text.setText("")
        self.r9text.setAlignment(QtCore.Qt.AlignCenter)
        self.r9text.setObjectName("r9text")
        self.verticalLayout_9.addWidget(self.r9text)
        self.r9photo = QtWidgets.QLabel(self.groupBox_2)
        self.r9photo.setStyleSheet("QLabel{\n"
"        background-color:rgb(240,240,240);\n"
"        border-radius:6px;\n"
"        border-color:grey grey grey grey;\n"
"        border-style:groove;\n"
"        border-width:2px    \n"
"}\n"
"\n"
"")
        self.r9photo.setText("")
        self.r9photo.setObjectName("r9photo")
        self.verticalLayout_9.addWidget(self.r9photo)
        self.r9text_2 = QtWidgets.QLabel(self.groupBox_2)
        self.r9text_2.setText("")
        self.r9text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.r9text_2.setObjectName("r9text_2")
        self.verticalLayout_9.addWidget(self.r9text_2)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 10)
        self.verticalLayout_9.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.r10text = QtWidgets.QLabel(self.groupBox_2)
        self.r10text.setText("")
        self.r10text.setAlignment(QtCore.Qt.AlignCenter)
        self.r10text.setObjectName("r10text")
        self.verticalLayout_10.addWidget(self.r10text)
        self.r10photo = QtWidgets.QLabel(self.groupBox_2)
        self.r10photo.setStyleSheet("QLabel{\n"
"        background-color:rgb(240,240,240);\n"
"        border-radius:6px;\n"
"        border-color:grey grey grey grey;\n"
"        border-style:groove;\n"
"        border-width:2px    \n"
"}\n"
"\n"
"")
        self.r10photo.setText("")
        self.r10photo.setObjectName("r10photo")
        self.verticalLayout_10.addWidget(self.r10photo)
        self.r10text_2 = QtWidgets.QLabel(self.groupBox_2)
        self.r10text_2.setText("")
        self.r10text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.r10text_2.setObjectName("r10text_2")
        self.verticalLayout_10.addWidget(self.r10text_2)
        self.verticalLayout_10.setStretch(0, 1)
        self.verticalLayout_10.setStretch(1, 10)
        self.verticalLayout_10.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_24.addLayout(self.horizontalLayout)
        self.verticalLayout_11.addWidget(self.groupBox_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.getphoto = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getphoto.sizePolicy().hasHeightForWidth())
        self.getphoto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.getphoto.setFont(font)
        self.getphoto.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.getphoto.setObjectName("getphoto")
        self.horizontalLayout_4.addWidget(self.getphoto)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.dopredict = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dopredict.sizePolicy().hasHeightForWidth())
        self.dopredict.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.dopredict.setFont(font)
        self.dopredict.setObjectName("dopredict")
        self.horizontalLayout_4.addWidget(self.dopredict)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 2)
        self.horizontalLayout_4.setStretch(4, 2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.verticalLayout_11.setStretch(0, 8)
        self.verticalLayout_11.setStretch(1, 8)
        self.verticalLayout_11.setStretch(2, 1)
        ReidSystem.setCentralWidget(self.centralwidget)

        self.retranslateUi(ReidSystem)
        QtCore.QMetaObject.connectSlotsByName(ReidSystem)

    def retranslateUi(self, ReidSystem):
        _translate = QtCore.QCoreApplication.translate
        ReidSystem.setWindowTitle(_translate("ReidSystem", "行人重识别查询软件"))
        self.groupBox_3.setTitle(_translate("ReidSystem", "查询图："))
        self.queryID.setText(_translate("ReidSystem", "ID"))
        self.query.setText(_translate("ReidSystem", "无图片"))
        self.groupBox_4.setTitle(_translate("ReidSystem", "设置："))
        self.label.setText(_translate("ReidSystem", "搜索模式："))
        self.mode.setItemText(0, _translate("ReidSystem", "红外搜索可见光"))
        self.mode.setItemText(1, _translate("ReidSystem", "可见光搜索红外"))
        self.label_2.setText(_translate("ReidSystem", "命令行窗口："))
        self.command.setHtml(_translate("ReidSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic; color:#868686;\">运行中的所有命令会显示在这里</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("ReidSystem", "运行结果："))
        self.getphoto.setText(_translate("ReidSystem", "   载入"))
        self.dopredict.setText(_translate("ReidSystem", "     搜索"))
